M48
; DRILL file {KiCad 8.0.8} date 2025-04-22T20:56:37-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-22T20:56:37-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.850
%
G90
G05
T1
X72.97Y-53.915
X72.97Y-110.915
X93.47Y-53.915
X93.47Y-110.915
T2
X106.11Y-90.76
X196.11Y-90.76
M30
